### ISSUE TITLE
Issue detected with Zod

### ISSUE THREAD

**Issue by vriad** [tuoxiansp/mould#2]
Just wanted to warn you that I found a bug in the inferred types of merged object schemas. Looks like you use `.merge` in multiple files. To the best of my knowledge, all runtime validation is working as expected. It's now fixed in zod@1.0.12 so I'd recommend upgrading so you don't get caught off guard. I'm implementing more thorough testing of the codebase to make sure this doesn't happen again...correct inferred types are kinda the whole reason I made zod so I feel a little dumb 😅

You're using Zod quite heavily so don't hesitate to reach out if you have any issues or feature requests!

**Comment by tuoxiansp** [comment]
Thanks very much! I'll upgrade after current work done 😄

**Comment by tuoxiansp** [comment]
@vriad upgraded
#6

**Comment by tuoxiansp** [comment]
#6
